### ISSUE TITLE
[bug] Does not Work With Expanded Trident Enchanting Installed

### ISSUE THREAD

**Issue by milkev** [realSmushyTaco/Expanded-Axe-Enchanting#2]
When [Expanded Trident Enchanting](https://www.curseforge.com/minecraft/mc-mods/expanded-trident-enchanting) is installed, this mod doesn't do anything. You can't put looting, knockback or fire aspect on an axe until expanded trident enchanting is removed.
I didn't see anything in the logs, but here they are anyway, if they happen to be of help.
[latest.log](https://github.com/realSmushyTaco/Expanded-Axe-Enchanting/files/6684772/latest.log)

**Comment by SmushyTaco** [comment]
The issue is that they both inject into the same method, might need to merge both mods into one mod to fix this, I'll look into this later today to see what I can do.

**Comment by SmushyTaco** [comment]
Alright I know how to fix it, not merging the mods together thankfully. I'll fix it tomorrow and push out an update then because I'm too lazy to do it right now.

**Comment by SmushyTaco** [comment]
Fixed.
