### ISSUE TITLE
[Bug] My game crash when I'm trying to use EasyAnvils and Expanded Axe Enchanting

### ISSUE THREAD

**Issue by CarlosAHT** [realSmushyTaco/Expanded-Axe-Enchanting#4]
[crash-2024-07-27_22.39.44-client.txt](https://github.com/user-attachments/files/16402291/crash-2024-07-27_22.39.44-client.txt)

I have these mods in my server, my game crash in the moment when I try to enchant with Unbreaking III my Diamond Axe with Mending and the game give me the crash report. Idk if is a problem from Expanded Axe or Easy Anvils.

**Comment by SmushyTaco** [comment]
I believe it's easy anvil causing this. The dynamic registry should 100% be initialized but the time you're able to use an anvil.
